### ISSUE TITLE
[[1.11.2]-2.1.9.113] Lumbinator Not Giving Correct # of Blocks

### ISSUE THREAD

**Issue by digitalnoise** [DuelMonster/SuperMiner#11]
I'm having an issue where Lumbinator is not giving the correct number of blocks when I cut down a tree.

For example, if I currently have 3 blocks in my inventory of the same type, and I chop down a tree 6 blocks high, I should end up with 9 blocks.

Instead, on average, I end up with 5 to 6 blocks (only gaining 2 - 3 instead of the entire 6)  So where did the other blocks go?

The only other mods I have (other than Forge) are:

Hwyla-1.8.5-B19_1.11
Inventory-Tweaks-1.11
journeymap-1.11.2-5.4.0
WailaHarvestability-1.11.2

**Comment by DuelMonster** [comment]
I have now had 2 reports of this issue and will look into it ASAP.

Must be a 1.11.x problem as I haven't seen this issue while playing in 1.10.2

**Comment by digitalnoise** [comment]
Thank you for looking into it - and I'll be happy to test for you if needed.

**Comment by DuelMonster** [comment]
Hey there, 
Could you please try the latest version and let me know if this is still an issue?

[[1.11.2]-2.1.10.114](https://minecraft.curseforge.com/projects/superminer-unified/files)

Thanks

**Comment by digitalnoise** [comment]
I'm sorry it's taken me so long to get back to you - it does appear that this is fixed in [1.11.2]-2.1.10.114, but only when starting a new game.

**Comment by Shinisuryu** [comment]
Having the same issue but on 1.10.2. No matter the size of the tree, it seems to only give 2 wood blocks.

**Comment by DuelMonster** [comment]
I've back ported the change to 1.10.2
Please retry thanks.

**Comment by Shinisuryu** [comment]
Will do as soon as I get home from work. About 6 hours left.

**Comment by Shinisuryu** [comment]
Tested with oak trees if it makes any difference. If you're right under the tree to pick up all the logs it works fine, but if you're far enough away to miss them, all but two disappear.

**Comment by DuelMonster** [comment]
Ok I'll take another look into it. Thnx for the info.

**Comment by Shinisuryu** [comment]
No problem, wanted to be sure I tested a few different ways of using it.

**Comment by DuelMonster** [comment]
@Shinisuryu  -  I've put out another update to try and solve this issue, but I'm having trouble replicating the problem...  I've tried all manner of tree types, sizes and tools, but always seem to get the expected amount of wood and stuff.  

In order for me to diagnose Lumbinator as to why it may be failing, would you be able to provide me with a few things?

If you have cloud storage, would you be able to get me a copy of the following items from your Minecraft instance?
- options.txt
- optionsof.txt (if using Opifine)
- your "config" folder
- your "mods" folder
- and a copy of you world folder from the "saves" folder

I know this seems a lot, but having all this may help me to find a solution/reason for it.  Just stick all the above into a zip file and share it with me.

I'd suggest you email me directly rather than putting a link here.  `SuperMiner@DuelMonster.co.uk`

Thanks,  DuelMonster

**Comment by Shinisuryu** [comment]
Will do!

**Comment by DuelMonster** [comment]
Solved with Releases:
- [1.11.2]-2.1.12.117
- [1.11]-2.1.12.114
- [1.10.2]-2.1.11.121
