### ISSUE TITLE
cropinator can not be turned on/off in game

### ISSUE THREAD

**Issue by crimso** [DuelMonster/SuperMiner#36]
Hello

I can not turn on/off the cropinator function in game, I also try to check what key I need to use but in the options control section the cropinator doesnt exist. I checked superminer config file the cropinator function is there but not in game.

Thank you

SuperMiner-2.6.34.336

**Comment by DuelMonster** [comment]
I am aware of this limitation and have factored this into the current re-write that I'm working on.

I'm 99% done with the re-write now and will be spending some time testing it thoroughly before releasing.  But you can expect the new release within the next couple of weeks.

**Comment by AveoCross** [comment]
How is update going?

**Comment by DuelMonster** [comment]
Hi @AveoCross,

I have a couple of niggly little issues I'm working on at the moment before I'm happy to release.  I'm just finding it hard to spend the time on it due to life, but hopefully not too much longer.

It will be released under a different name as well, as I feel it deserves it due to only 95% of the code stems from the original.

**Comment by AveoCross** [comment]
Will it be available for 1.10.2? I just tested probably all tree cutting mods for 1.10.2 and nothing fulfills my needs :c

**Comment by DuelMonster** [comment]
I was only planning on a 1.12 release.

However I will look at how much work would be involved in down porting.

**Comment by DuelMonster** [comment]
REWRITE COMPLETE - MinersAdvantage released!!

https://github.com/DuelMonster/MinersAdvantage
